frappe/helm

- RELEASE.md
- release_wizard/requirements.txt
- release_wizard/wizard
> fix: release wizard

- erpnext/templates/job-migrate-sites.yaml
set maintenance mode even before backup
> fix: migrate job

- faq.md
- prepare-kubernetes/index.md
add reference to cert-manager ClusterIssuer docs
> docs: add steps for beginners in FAQ

- erpnext/Chart.yaml
- Use release script
- DO NOT manually tag
- now re tag to 1.0.2 after merging this.
> fix: version in chart set to version in tag

- faq.md
do not forget to update cronjob after upgrade
> docs: note to update instruction

- release_wizard/wizard
> feat: check for git ssh command

- kubernetes-resources/create-new-site-job-postgresql.md
- kubernetes-resources/index.md
- prepare-kubernetes/mariadb.md
ping secondary postgresql service if frappe-postgres site is created
> docs: ping optional postgres services using doctor

- erpnext/templates/deployment-scheduler.yaml
- erpnext/templates/deployment-worker-default.yaml
- erpnext/templates/deployment-worker-long.yaml
- erpnext/templates/deployment-worker-short.yaml
- erpnext/values.yaml
ping secondary postgresql service if frappe-postgres site is created
> feat: ping optional postgres services using doctor

- erpnext/README.md
> Please provide enough information so that others can review your pull request:
> Explain the **details** for making this change. What existing problem does the pull request solve?
> docs: Fix typo "MariaDB"

- erpnext/templates/deployment-scheduler.yaml
- erpnext/templates/deployment-worker-default.yaml
- erpnext/templates/deployment-worker-long.yaml
- erpnext/templates/deployment-worker-short.yaml
use shell script instead of python
> fix: health check

- erpnext/README.md
- erpnext/templates/deployment-erpnext.yaml
- erpnext/values.yaml
> feat: allow configuring realip module for nginx

- faq.md
- index.md
- kubernetes-resources/create-new-site-job-postgresql.md
https://github.com/frappe/helm/pull/69
> docs: update docs for related PR

- erpnext/templates/deployment-redis-cache.yaml
- erpnext/templates/deployment-redis-queue.yaml
- erpnext/templates/deployment-redis-socketio.yaml
> fix: cli args for built in redis deployments

- .travis.yml
fixes #76
moved the job from deploy to jobs > stage
@Thunderbottom can you review.
If you have any idea if it will work with travis as expected?
using condition
`if: branch = master AND tag IS present`
> ci: publish script as job stage

- .travis.yml
> ci: fix test and deploy

- .travis.yml
https://github.com/frappe/helm/issues/76#issuecomment-817103261
> ci: skip test if not PR

- erpnext/README.md
- erpnext/templates/ingress.yaml
- erpnext/templates/job-create-site.yaml
- erpnext/templates/pre-delete-drop-site-job.yaml
- erpnext/templates/secret.yaml
- erpnext/values.yaml
option to delete site on helm uninstall
#83
> feat: optionally create site with helm release

- erpnext/templates/ingress.yaml
- erpnext/templates/job-create-site.yaml
- erpnext/templates/pre-delete-drop-site-job.yaml
fixes https://github.com/frappe/helm/issues/85
> fix: reduce size of post delete job name

- erpnext/templates/job-create-site.yaml
- erpnext/templates/job-migrate-sites.yaml
- erpnext/templates/pre-delete-drop-site-job.yaml
- fix image pull fail from private registry during job creation
- identify jobs with labels
> fix: add imagePullSecrets and labels to chart Jobs

- erpnext/templates/serviceaccount.yaml
> fix: remove duplicate label in serviceaccount.yaml

- erpnext/templates/deployment-erpnext.yaml
- erpnext/values.yaml
securityContext is configurable from values
closes #105 and #106
> fix: volumePermissions flag

- prepare-kubernetes/index.md
> fix: typo K8s

- erpnext/templates/deployment-erpnext.yaml
- erpnext/templates/deployment-scheduler.yaml
- erpnext/templates/deployment-worker-default.yaml
- erpnext/templates/deployment-worker-long.yaml
- erpnext/templates/deployment-worker-short.yaml
make changes for refactor (https://github.com/frappe/frappe_docker/pull/617) to work on existing setups
> fix: make changes for backward compat

- erpnext/templates/job-configure-bench.yaml
https://github.com/fluxcd/helm-controller/issues/383
This branch has been manually tested on a kubernetes cluster bare metal
> Multiline args string

- release_wizard/requirements.txt
- release_wizard/wizard
> update: release script

- erpnext/Chart.yaml
- erpnext/values.yaml
> fix: upgrade redis, postgresql, mariadb chart versions

- erpnext/templates/job-fix-volume-permission.yaml
> Please provide enough information so that others can review your pull request:
> Explain the **details** for making this change. What existing problem does the pull request solve?
> fix reference image

- erpnext/Chart.yaml
> chore: update icon

- erpnext/templates/deployment-socketio.yaml
> fix: socketio deployment nodeSelector

- README.md
> docs: explain additional resources in repo readme

- erpnext/templates/hpa-gunicorn.yaml
- erpnext/templates/hpa-nginx.yaml
- erpnext/templates/hpa-socketio.yaml
- erpnext/templates/hpa-worker-default.yaml
- erpnext/templates/hpa-worker-long.yaml
- erpnext/templates/hpa-worker-short.yaml
> Please provide enough information so that others can review your pull request:
> Explain the **details** for making this change. What existing problem does the pull request solve?
> Changed API Version in HPA files from autoscaling/v1 to autoscaling/v2

- erpnext/README.md
- erpnext/templates/job-backup.yaml
- erpnext/templates/job-configure-bench.yaml
- erpnext/templates/job-create-site.yaml
- erpnext/templates/job-drop-site.yaml
- erpnext/templates/job-fix-volume-permission.yaml
- erpnext/templates/job-migrate-site.yaml
- erpnext/values.yaml
- set jobName for manual job naming
> feat: configurable job names
